import Head from "next/head";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  const { hostel, floor, room } = router.query;
  return (
    <div>
      <Head>
        <title>r/IITH </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
            Welcome to room {room} on floor {floor} of hostel {hostel}
        </h1>
      </main>
    </div>
  );
}