import { Box, Button, Grid } from '@mantine/core'
import Head from 'next/head'
import { useRouter } from 'next/router'
export default function Home() {
  const router = useRouter()
  const { hostel, floor } = router.query
  const pods = []
  for (let i = 0; i < 4; i++) {
    pods.push(
      <Grid columns={8}>
        <Grid.Col span={2} offset={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + 4}`}
          >
            {`${i * 8 + 4}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + 3}`}
          >
            {`${i * 8 + 3}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}></Grid.Col>
        <Grid.Col span={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + 5}`}
          >
            {`${i * 8 + 5}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2} offset={4}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + 2}`}
          >
            {`${i * 8 + 2}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + 6}`}
          >
            {`${i * 8 + 6}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2} offset={4}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + 1}`}
          >
            {`${i * 8 + 1}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2} offset={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + 7}`}
          >
            {`${i * 8 + 7}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + 8}`}
          >
            {`${i * 8 + 8}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}></Grid.Col>
      </Grid>
    )
  }

  return (
    <div>
      <Head>
        <title>r/IITH </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to floor {floor} hostel {hostel}
        </h1>
        <Grid columns={2}>
          <Grid.Col span={1}>
            <Grid columns={2}>
              {pods.slice(0, 2).map((pod, index) =>
                index === 0 ? (
                  <>
                    <Grid.Col key={index} span={1}>
                      {pod}
                    </Grid.Col>
                    <Grid.Col span={1}></Grid.Col>
                  </>
                ) : (
                  <>
                    <Grid.Col span={1}></Grid.Col>

                    <Grid.Col key={index} span={1}>
                      {pod}
                    </Grid.Col>
                  </>
                )
              )}
            </Grid>
          </Grid.Col>
          <Grid.Col span={1}>
            <Grid columns={2}>
              {pods.slice(2, 4).map((pod, index) =>
                index === 0 ? (
                  <>
                    <Grid.Col key={index} span={1}>
                      {pod}
                    </Grid.Col>
                    <Grid.Col span={1}></Grid.Col>
                  </>
                ) : (
                  <>
                    <Grid.Col span={1}></Grid.Col>

                    <Grid.Col key={index} span={1}>
                      {pod}
                    </Grid.Col>
                  </>
                )
              )}
            </Grid>
          </Grid.Col>
        </Grid>
      </main>
    </div>
  )
}
