import { Box, Button, Grid, AppShell, useMantineTheme } from '@mantine/core'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Nav } from '../../../../components/Header'
export default function Home() {
  const router = useRouter()
  const { hostel, floor } = router.query
  const pods = []
  for (let i = 0; i < 4; i++) {
    pods.push(
      <Grid columns={8}>
        <Grid.Col span={2} offset={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + (i%2==0?5: 1)}`}
          >
            {`${i * 8 + (i%2==0?5: 1)}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + (i%2==0?6: 2)}`}
          >
            {`${i * 8 + (i%2==0?6: 2)}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}></Grid.Col>
        <Grid.Col span={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + (i%2==0?4: 8)}`}
          >
            {`${i * 8 + (i%2==0?4: 8)}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2} offset={4}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + (i%2==0?7: 3)}`}
          >
            {`${i * 8 + (i%2==0?7: 3)}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + (i%2==0?3:7)}`}
          >
            {`${i * 8 + (i%2==0?3:7)}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2} offset={4}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + (i%2==0?8:4)}`}
          >
            {`${i * 8 + (i%2==0?8:4)}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2} offset={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + (i%2==0?2:6)}`}
          >
            {`${i * 8 + (i%2==0?2:6)}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}>
          <Button
            component="a"
            href={`/hostels/${hostel}/${floor}/${floor * 100 + i * 8 + (i%2==0?1:5)}`}
          >
            {`${i * 8 + (i%2==0?1:5)}`}
          </Button>
        </Grid.Col>
        <Grid.Col span={2}></Grid.Col>
      </Grid>
    )
  }
  const theme = useMantineTheme()
  return (
    <>
      <Head>
        <title>r/IITH </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        styles={{
          main: {
            background:
              theme.colorScheme === 'dark'
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        }}
        navbarOffsetBreakpoint="sm"
        header={<Nav />}
      >

        <h1>
          Welcome to floor {floor} hostel {hostel}
        </h1>
        <Grid columns={2}>
          <Grid.Col span={1}>
            <Grid columns={2}>
              {pods.slice(0, 2).map((pod, index) =>
                index === 0 ? (
                  <>
                    <Grid.Col key={index} span={1}>
                      {pod}
                    </Grid.Col>
                    <Grid.Col span={1}></Grid.Col>
                  </>
                ) : (
                  <>
                    <Grid.Col span={1}></Grid.Col>
                    <Grid.Col key={index} span={1}>
                      {pod}
                    </Grid.Col>
                  </>
                )
              )}
            </Grid>
          </Grid.Col>
          <Grid.Col span={1}>
            <Grid columns={2}>
              {pods.slice(2, 4).map((pod, index) =>
                index === 0 ? (
                  <>
                    <Grid.Col key={index} span={1}>
                      {pod}
                    </Grid.Col>
                    <Grid.Col span={1}></Grid.Col>
                  </>
                ) : (
                  <>
                    <Grid.Col span={1}></Grid.Col>
                    <Grid.Col key={index} span={1}>
                      {pod}
                    </Grid.Col>
                  </>
                )
              )}
            </Grid>
          </Grid.Col>
        </Grid>
      </AppShell>
    </>
  )
}
