import Head from "next/head";
import Login from "../components/Login";
import Canvas from "../components/Canvas";
export default function Home() {
  return (
    <div>
      <Head>
        <title>R-Place | IITH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Canvas />
      </main>
    </div>
  );
}
