import { Stack, Box, Button } from '@mantine/core'
import Head from 'next/head'
import { useRouter } from 'next/router'
export default function Home() {
  const router = useRouter()
  const { hostel } = router.query
  return (
    <>
      <Head>
        <title>r/IITH </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to hostel {hostel}</h1>
      <Box
        sx={{
          alignItems: 'center',
          width: '200px',
          margin: 'auto',
          padding: '30px 10px 30px 10px',
          border: '1px solid #ccc',
        }}
      >
        <Stack spacing="xs">
          <Button component="a" href={`/hostels/${hostel}/1`}>
            Floor 1
          </Button>
          <Button component="a" href={`/hostels/${hostel}/2`}>
            Floor 2
          </Button>
          <Button component="a" href={`/hostels/${hostel}/3`}>
            Floor 3
          </Button>
          <Button component="a" href={`/hostels/${hostel}/4`}>
            Floor 4
          </Button>
          <Button component="a" href={`/hostels/${hostel}/5`}>
            Floor 5
          </Button>
          <Button component="a" href={`/hostels/${hostel}/6`}>
            Floor 6
          </Button>
        </Stack>
      </Box>
    </>
  )
}
