import Head from 'next/head'
import { useRouter } from 'next/router'
import {
  Button,
  Box,
  createStyles,
  rem,
  Grid,
  AppShell,
  useMantineTheme,
  Modal,
  Group,
  Stack,
  Text,
  Image,
} from '@mantine/core'
import { useDisclosure } from '@mantine/hooks'
import { useState, useContext } from 'react'
import { Nav } from '../../components/Header'
import AppContext from '../../AppContext'

const useStyles = createStyles((theme) => ({
  button: {
    display: 'block',
    lineHeight: 1,
    padding: `${rem(8)} ${rem(12)}`,
    borderRadius: theme.radius.sm,
    textDecoration: 'none',
    color: theme.colors.green[9],
    fontSize: theme.fontSizes.md,
    fontWeight: 500,
    backgroundColor: theme.colors.green[0],
    position: 'absolute',
    zIndex: '100',
    width: '12rem',
    height: '6rem',
    // visibility: 'hidden',

    opacity: 0,
    '&:hover': {
      transition: 'all linear .3s',
      // visibility: 'visible',
      opacity: 1,
      cursor: 'pointer',
      backgroundColor: theme.colors.green[2],
    },
  },
}))
export default function Home() {
  const theme = useMantineTheme()
  const { classes, cx } = useStyles()
  const value = useContext(AppContext)
  let globalData = value.state.globalData
  const { hostel_names } = globalData
  
  const [opened, { open, close }] = useDisclosure(false)
  const [hostel, setHostel] = useState(0)
  return (
    <>
      <Head>
        <title>r/IITH </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        styles={{
          main: {
            background:
              theme.colorScheme === 'dark'
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        }}
        navbarOffsetBreakpoint="sm"
        header={<Nav />}
      >
        <Text
          variant="gradient"
          gradient={{ from: 'indigo', to: 'cyan', deg: 45 }}
          ta="center"
          sx={{
            fontSize: '3rem',
          }}
          fw={700}
        >
          Welcome to IIT Hyderbad
        </Text>
        <Modal opened={opened} onClose={close} title={`Welcome to ${hostel_names[hostel]}`} centered>
        <Box
          sx={{
            alignItems: 'center',
            width: '200px',
            margin: 'auto',
            padding: '30px 10px 30px 10px',
            border: '1px solid #ccc',
          }}
        >
          <Stack spacing="xs">
            <Button component="a" href={`/hostels/${hostel}/1`}>
              Floor 1
            </Button>
            <Button component="a" href={`/hostels/${hostel}/2`}>
              Floor 2
            </Button>
            <Button component="a" href={`/hostels/${hostel}/3`}>
              Floor 3
            </Button>
            <Button component="a" href={`/hostels/${hostel}/4`}>
              Floor 4
            </Button>
            <Button component="a" href={`/hostels/${hostel}/5`}>
              Floor 5
            </Button>
            <Button component="a" href={`/hostels/${hostel}/6`}>
              Floor 6
            </Button>
          </Stack>
        </Box>
      </Modal>
        <Box
          sx={{
            position: 'relative',
            margin: '3rem auto',
          }}
          maw={800}
        >
          <Image
            src={
              'https://res.cloudinary.com/dcpgsijmr/image/upload/v1686818820/r-place/hostels_afidd9.png'
            }
            maw={800}
            mx="auto"
            radius="md"
            alt={'hostels IITH'}
          />

          {[
            { top: '5rem', left: -20, transform: 'rotate(90deg)' },
            { top: '1.5rem', left: '11rem' },
            { top: '5rem', right: '14rem', transform: 'rotate(90deg)' },
            { top: '1.5rem', right: '2rem' },
            // round 2
            { top: '14rem', right: -20, transform: 'rotate(90deg)' },
            { top: '17rem', right: '11rem' },
            { top: '14rem', left: '14rem', transform: 'rotate(90deg)' },
            { top: '17rem', left: '2rem' },
            // round 3
            { bottom: '11rem', left: '6rem' },
            { bottom: '1.5rem', left: '6rem' },
          ].map((item, index) => (
            <button
              className={classes.button}
              style={{ ...item }}
              onClick={() => {
                setHostel(index);
                open();
              }}
            >
              {hostel_names[index]}
            </button>
          ))}
        </Box>
      </AppShell>
    </>
  )
}
